services:
  api:
    image: deardiary-api
    build:
      context: ./API/DearDiary.API/DearDiary.API
      dockerfile: Dockerfile
    container_name: deardiary-api
    ports:
      - "7078:8080"
    depends_on:
      db:
        condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ConnectionStrings__DefaultConnection=Server=db;Database=DearDiaryDb;User Id=sa;Password=YourStrong@123;TrustServerCertificate=True;
    networks:
      - deardiary-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: deardiary-db
    environment:
      SA_PASSWORD: "YourStrong@123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - deardiary-network
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'YourStrong@123' -C -Q 'SELECT 1' || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 60s

  adminer:
    image: adminer
    container_name: deardiary-adminer
    ports:
      - "8081:8080"
    networks:
      - deardiary-network
    depends_on:
      - db

volumes:
  sqlserver_data:

networks:
  deardiary-network:
    driver: bridge

